# Generated by Django 4.0.2 on 2022-04-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_attraction_with_adults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='with_adults',
            field=models.CharField(max_length=200, verbose_name='посещение со взрослыми'),
        ),
    ]
