# Generated by Django 4.0.2 on 2022-04-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_attraction_with_adults'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='избранный'),
        ),
    ]
