# Generated by Django 4.0.2 on 2022-04-19 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_attraction_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attraction',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='редактировался'),
        ),
    ]
