# Generated by Django 4.0.4 on 2022-04-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_attraction_created_attraction_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='sorting',
            field=models.IntegerField(default=100, verbose_name='Сортировка'),
        ),
    ]
