# Generated by Django 4.0.4 on 2022-05-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_attraction_sorting'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='additional_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Дополнительная ссылка'),
        ),
    ]
