# Generated by Django 4.0.4 on 2022-05-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_attraction_additional_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={'ordering': ('sorting', 'title'), 'verbose_name': 'Аттракцион', 'verbose_name_plural': 'Аттракционы'},
        ),
        migrations.AlterField(
            model_name='attraction',
            name='height',
            field=models.IntegerField(default=100, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='title',
            field=models.CharField(help_text='название аттракциона', max_length=300, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='with_adults',
            field=models.CharField(blank=True, max_length=200, verbose_name='посещение со взрослыми'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='work_time',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
